project_0:
  url: "/"
  description: "Environment Set Up"
project_1:
  url: "./home"
  description: "Custom Home Page Route"
project_2:
  url: "./project_2"
  description: "Description of Bootstrap set up"
